# Generated by Django 5.2.5 on 2025-09-10 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Video Title')),
                ('video_file', models.FileField(upload_to='event_videos/', verbose_name='Video File')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='events.event', verbose_name='Related Event')),
            ],
            options={
                'verbose_name': 'Event Video',
                'verbose_name_plural': 'Event Videos',
            },
        ),
    ]
